{{- if and .Values.recoveryAdmin.enabled (not .Values.recoveryAdmin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart.envSecretName" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.recoveryAdmin.username | quote }}
  password: {{ required "recoveryAdmin.password is required when existingSecret is empty" .Values.recoveryAdmin.password | quote }}
  STALWART_RECOVERY_ADMIN: {{ printf "%s:%s" .Values.recoveryAdmin.username .Values.recoveryAdmin.password | quote }}
  {{- range $key, $value := .Values.extraSecretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else if and (not .Values.recoveryAdmin.existingSecret) .Values.extraSecretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart.envSecretName" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.extraSecretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
