apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}-headless
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    - name: mgmt
      port: {{ .Values.service.ports.mgmt }}
      targetPort: mgmt
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    - name: tcp-smtp
      port: {{ .Values.service.ports.smtp }}
      targetPort: smtp
    - name: tcp-smtps
      port: {{ .Values.service.ports.smtps }}
      targetPort: smtps
    - name: tcp-submission
      port: {{ .Values.service.ports.submission }}
      targetPort: submission
    - name: tcp-imap
      port: {{ .Values.service.ports.imap }}
      targetPort: imap
    - name: tcp-imaps
      port: {{ .Values.service.ports.imaps }}
      targetPort: imaps
    - name: tcp-pop3
      port: {{ .Values.service.ports.pop3 }}
      targetPort: pop3
    - name: tcp-pop3s
      port: {{ .Values.service.ports.pop3s }}
      targetPort: pop3s
    - name: tcp-sieve
      port: {{ .Values.service.ports.sieve }}
      targetPort: sieve
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: https
    - name: mgmt
      port: {{ .Values.service.ports.mgmt }}
      targetPort: mgmt
{{- if .Values.mailLoadBalancer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.fullname" . }}-mail
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
  {{- with .Values.mailLoadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mailLoadBalancer.type }}
  {{- with .Values.mailLoadBalancer.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "stalwart.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.mailLoadBalancer.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
{{- end }}
