apiVersion: v2
name: stalwart
description: Stalwart mail server for dbslone.com and simplefbo.com
type: application
version: 0.1.3
appVersion: "v0.16.20"
home: https://stalw.art
sources:
  - https://github.com/stalwartlabs/stalwart
  - https://stalw.art/docs/cluster/orchestration/kubernetes/
