{{- if and (not .Values.session.existingSecret) .Values.session.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bulwark.sessionSecretName" . }}
  labels:
    {{- include "bulwark.labels" . | nindent 4 }}
type: Opaque
stringData:
  SESSION_SECRET: {{ .Values.session.secret | quote }}
{{- end }}
