apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: api-gateway
  namespace: simplefbo
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.simplefbo.com"
    - "api.dbslone.com"
  # - port:
  #     number: 443
  #     name: https
  #     protocol: HTTPS
    # tls:
    #   mode: SIMPLE
    #   credentialName: api-simplefbo-tls  # Reference to Secret with TLS cert
    hosts:
    - "api.simplefbo.com"
    - "api.dbslone.com"