apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-gateway-vs
  namespace: simplefbo
  labels:
    {{- include "gateway-helm.labels" . | nindent 4 }}
spec:
  hosts:
    - "api.simplefbo.com"
    - "api.dbslone.com"
  gateways:
    - istio-ingress/api-gateway
  http:
    - match:
        - uri:
            prefix: /graphql
      {{- include "istio.corsPolicy" . | nindent 6 }}
      route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
    - match:
        - uri:
            prefix: /subscriptions
      {{- include "istio.corsPolicy" . | nindent 6 }}
      route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
    - match:
        - uri:
            prefix: /user
      {{- include "istio.corsPolicy" . | nindent 6 }}
      route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
    - match:
        - uri:
            prefix: /admin
      {{- include "istio.corsPolicy" . | nindent 6 }}
      route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
    - match:
        - uri:
            prefix: /squawk
      {{- include "istio.corsPolicy" . | nindent 6 }}
      route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
    - match:
        - uri:
            prefix: /checkout
      {{- include "istio.corsPolicy" . | nindent 6 }}
      route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
    - match:
        - uri:
            prefix: /squawkLog
      {{- include "istio.corsPolicy" . | nindent 6 }}
      route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
    - match:
        - uri:
            prefix: /aircraft
      {{- include "istio.corsPolicy" . | nindent 6 }}
      route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
    - match:
        - uri:
            prefix: /signup
      {{- include "istio.corsPolicy" . | nindent 6 }}
      route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
    - match:
        - uri:
            prefix: /actuator
      route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
    - route:
        - destination:
            host: mvn-backend-simplefbo-backend.simplefbo.svc.cluster.local
            port:
              number: 8003
