name: Update Index

on:
  push:
    branches: [ main ]
    paths:
      - '**.tgz'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v7
      - name: Setup Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Helm Installation
        uses: azure/setup-helm@v4
      - name: Update Index
        run: |
          helm repo index .
          git config --global user.email "dbslone@gmail.com"
          git config --global user.name "SimpleFBO"
          git add index.yaml
          git commit -m "Update chart index"
          git push